services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: krapidb
      MYSQL_USER: krapi
      MYSQL_PASSWORD: krapi
    ports:
      - 23306:3306
    volumes:
      - ./mysql:/var/lib/mysql

